var questions_en_level4_data = [
  {
    question: "What is the capital of Australia?",
    translation: "澳洲的首都是什麼？",
    answers: [
      {
        text: "Sydney",
        correct: false,
        translation: "雪梨",
        fact: "Sydney is Australia's largest city and a major global financial hub.",
        fact_zh: "雪梨是澳洲最大的城市和主要的全球金融中心。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Melbourne",
        correct: false,
        translation: "墨爾本",
        fact: "Melbourne is known for its vibrant arts scene and cultural institutions.",
        fact_zh: "墨爾本以其充滿活力的藝術氛圍和文化機構而聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Canberra",
        correct: true,
        translation: "坎培拉",
        fact: "Canberra is the capital city of Australia, chosen as a compromise between rival cities Sydney and Melbourne.",
        fact_zh:
          "坎培拉是澳洲的首都，是作為競爭對手城市雪梨和墨爾本之間的折衷方案而選定的。",
        correctFact:
          "It is an entirely planned city, designed by American architects Walter Burley Griffin and Marion Mahony Griffin.",
        correctFact_zh:
          "它是一個完全規劃的城市，由美國建築師華特·貝理·格里芬和瑪莉安·馬奧尼·格里芬設計。跟一般人印象中的澳洲大城不太一樣喔！",
      },
      {
        text: "Perth",
        correct: false,
        translation: "伯斯",
        fact: "Perth is the capital of Western Australia.",
        fact_zh: "伯斯是西澳州的首府。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the primary language spoken in Brazil?",
    translation: "巴西的主要官方語言是什麼？",
    answers: [
      {
        text: "Spanish",
        correct: false,
        translation: "西班牙語",
        fact: "Spanish is spoken in most other South American countries.",
        fact_zh: "西班牙語在大多數其他南美國家使用。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "English",
        correct: false,
        translation: "英語",
        fact: "English is not an official language in Brazil.",
        fact_zh: "英語不是巴西的官方語言。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Portuguese",
        correct: true,
        translation: "葡萄牙語",
        fact: "Portuguese is the official language of Brazil, a legacy of its colonization by Portugal.",
        fact_zh: "葡萄牙語是巴西的官方語言，這是葡萄牙殖民統治的遺產。",
        correctFact:
          "Brazilian Portuguese has developed some differences from European Portuguese in terms of pronunciation, vocabulary, and grammar.",
        correctFact_zh:
          "巴西葡萄牙語在發音、詞彙和語法方面與歐洲葡萄牙語產生了一些差異。足球王國講的不是西班牙文喔！",
      },
      {
        text: "French",
        correct: false,
        translation: "法語",
        fact: "French is not widely spoken in Brazil.",
        fact_zh: "法語在巴西並不普遍使用。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the most abundant gas in Earth's atmosphere?",
    translation: "地球大氣中含量最多的氣體是什麼？",
    answers: [
      {
        text: "Oxygen",
        correct: false,
        translation: "氧氣",
        fact: "Oxygen makes up about 21% of the Earth's atmosphere.",
        fact_zh: "氧氣約佔地球大氣的21%。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Carbon Dioxide",
        correct: false,
        translation: "二氧化碳",
        fact: "Carbon dioxide is a trace gas, important for the greenhouse effect.",
        fact_zh: "二氧化碳是一種微量氣體，對溫室效應很重要。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Nitrogen",
        correct: true,
        translation: "氮氣",
        fact: "Nitrogen makes up about 78% of Earth's atmosphere, making it the most abundant gas.",
        fact_zh: "氮氣約佔地球大氣的78%，是含量最多的氣體。",
        correctFact:
          "Although abundant, atmospheric nitrogen is relatively unreactive and must be 'fixed' into usable forms by bacteria or lightning for biological processes.",
        correctFact_zh:
          "雖然含量豐富，但大氣中的氮氣相對不活潑，必須由細菌或閃電「固定」成可用形式才能參與生物過程。我們呼吸的空氣中，氮氣其實最多！",
      },
      {
        text: "Argon",
        correct: false,
        translation: "氬氣",
        fact: "Argon is a noble gas and makes up less than 1% of the atmosphere.",
        fact_zh: "氬氣是一種惰性氣體，佔大氣的比例不到1%。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "In what year did the first human walk on the Moon?",
    translation: "人類首次登陸月球是在哪一年？",
    answers: [
      {
        text: "1965",
        correct: false,
        translation: "1965年",
        fact: "This was before the Moon landing.",
        fact_zh: "這是在登月之前。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "1971",
        correct: false,
        translation: "1971年",
        fact: "Later Apollo missions occurred in this year.",
        fact_zh: "後來的阿波羅任務發生在這一年。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "1969",
        correct: true,
        translation: "1969年",
        fact: "Neil Armstrong became the first person to walk on the Moon on July 20, 1969, during the Apollo 11 mission.",
        fact_zh:
          "尼爾·阿姆斯壯於1969年7月20日在阿波羅11號任務期間成為第一個踏上月球的人。",
        correctFact:
          "This historic event was watched by an estimated 600 million people worldwide, making it the largest television audience for a single event at that time.",
        correctFact_zh:
          "這一歷史性事件估計有6億人觀看，使其成為當時單一事件的最大電視觀眾群。真的是「我的一小步，人類一大步」！",
      },
      {
        text: "1973",
        correct: false,
        translation: "1973年",
        fact: "The last Apollo mission to the Moon was in 1972.",
        fact_zh: "最後一次阿波羅登月任務是在1972年。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the chemical symbol for Iron?",
    translation: "鐵的化學符號是什麼？",
    answers: [
      {
        text: "Ir",
        correct: false,
        translation: "Ir",
        fact: "Ir is the chemical symbol for Iridium.",
        fact_zh: "Ir 是銥 (Iridium) 的化學符號。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Fe",
        correct: true,
        translation: "Fe",
        fact: "Fe is the chemical symbol for Iron, derived from its Latin name 'ferrum'.",
        fact_zh: "Fe 是鐵 (Iron) 的化學符號，源自其拉丁名稱「ferrum」。",
        correctFact:
          "Iron is a common metal, crucial for many biological processes and a primary component of steel.",
        correctFact_zh:
          "鐵是一種常見金屬，對許多生物過程至關重要，也是鋼鐵的主要成分。我們吃的紅肉裡面就有鐵質喔！",
      },
      {
        text: "Io",
        correct: false,
        translation: "Io",
        fact: "Io is one of Jupiter's moons.",
        fact_zh: "Io 是木星的衛星之一，不是化學元素。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "In",
        correct: false,
        translation: "In",
        fact: "In is the chemical symbol for Indium.",
        fact_zh: "In 是銦 (Indium) 的化學符號。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "In which year did the Titanic sink?",
    translation: "鐵達尼號在哪一年沉沒？",
    answers: [
      {
        text: "1910",
        correct: false,
        translation: "1910年",
        fact: "The Titanic was still under construction in 1910.",
        fact_zh: "鐵達尼號在1910年仍在建造中。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "1912",
        correct: true,
        translation: "1912年",
        fact: "The RMS Titanic sank in the early morning of April 15, 1912, on its maiden voyage from Southampton to New York City.",
        fact_zh:
          "鐵達尼號於1912年4月15日凌晨在其從南安普敦到紐約市的處女航中沉沒。",
        correctFact:
          "It struck an iceberg in the North Atlantic Ocean, leading to the deaths of more than 1,500 people.",
        correctFact_zh:
          "它在北大西洋撞上冰山，導致超過1500人死亡。電影《鐵達尼號》就是根據這個真實事件改編的。",
      },
      {
        text: "1914",
        correct: false,
        translation: "1914年",
        fact: "World War I began in 1914.",
        fact_zh: "第一次世界大戰於1914年開始。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "1916",
        correct: false,
        translation: "1916年",
        fact: "This was during World War I.",
        fact_zh: "這是在第一次世界大戰期間。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question:
      "Which instrument is used to measure the intensity of earthquakes?",
    translation: "測量地震強度的儀器是什麼？",
    answers: [
      {
        text: "Barometer",
        correct: false,
        translation: "氣壓計",
        fact: "A barometer measures atmospheric pressure.",
        fact_zh: "氣壓計測量大氣壓力。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Anemometer",
        correct: false,
        translation: "風速計",
        fact: "An anemometer measures wind speed.",
        fact_zh: "風速計測量風速。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Seismograph (Seismometer)",
        correct: true,
        translation: "地震儀",
        fact: "A seismograph is an instrument used to detect and record seismic waves caused by earthquakes.",
        fact_zh: "地震儀是用於偵測和記錄由地震引起的地震波的儀器。",
        correctFact:
          "Modern seismographs are highly sensitive and can detect ground motions from earthquakes occurring anywhere in the world.",
        correctFact_zh:
          "現代地震儀非常靈敏，可以偵測到世界任何地方發生的地震所引起的地面運動。台灣位處地震帶，地震儀對我們很重要！",
      },
      {
        text: "Thermometer",
        correct: false,
        translation: "溫度計",
        fact: "A thermometer measures temperature.",
        fact_zh: "溫度計測量溫度。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "In what year did World War II end?",
    translation: "第二次世界大戰在哪一年結束？",
    answers: [
      {
        text: "1943",
        correct: false,
        translation: "1943年",
        fact: "This was during the middle of WWII.",
        fact_zh: "這是在第二次世界大戰中期。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "1944",
        correct: false,
        translation: "1944年",
        fact: "D-Day occurred in 1944.",
        fact_zh: "諾曼第登陸發生在1944年。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "1945",
        correct: true,
        translation: "1945年",
        fact: "World War II officially ended with the formal surrender of Japan on September 2, 1945, following the atomic bombings of Hiroshima and Nagasaki and the Soviet invasion of Manchuria.",
        fact_zh:
          "第二次世界大戰隨著日本於1945年9月2日正式投降而正式結束，此前發生了廣島和長崎原子彈爆炸以及蘇聯入侵滿洲。",
        correctFact:
          "V-J Day (Victory over Japan Day) is celebrated on September 2nd in the United States, while other countries observe it on August 15th.",
        correctFact_zh:
          "美國於9月2日慶祝對日戰爭勝利紀念日（V-J Day），而其他國家則在8月15日慶祝。這場戰爭對全世界影響深遠。",
      },
      {
        text: "1946",
        correct: false,
        translation: "1946年",
        fact: "This was after the end of WWII.",
        fact_zh: "這是在第二次世界大戰結束之後。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Who developed the theory of evolution by natural selection?",
    translation: "誰提出了藉由自然選擇演化的理論？",
    answers: [
      {
        text: "Gregor Mendel",
        correct: false,
        translation: "格雷戈爾·孟德爾",
        fact: "Gregor Mendel is known as the father of genetics for his work on pea plants.",
        fact_zh: "孟德爾是遺傳學之父，提出了遺傳定律。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Albert Einstein",
        correct: false,
        translation: "阿爾伯特·愛因斯坦",
        fact: "Albert Einstein developed the theory of relativity.",
        fact_zh: "愛因斯坦發展了相對論。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Charles Darwin",
        correct: true,
        translation: "查爾斯·達爾文",
        fact: "Charles Darwin was an English naturalist, geologist, and biologist, best known for his contributions to the science of evolution.",
        fact_zh:
          "查爾斯·達爾文是英國博物學家、地質學家和生物學家，以其對演化科學的貢獻而聞名。",
        correctFact:
          "His book 'On the Origin of Species' (1859) introduced the theory that populations evolve over the course of generations through a process of natural selection.",
        correctFact_zh:
          "他的著作《物種起源》（1859年）介紹了族群透過自然選擇過程世代演化的理論。「物競天擇，適者生存」就是這個理論的核心概念。",
      },
      {
        text: "Louis Pasteur",
        correct: false,
        translation: "路易·巴斯德",
        fact: "Louis Pasteur made significant contributions to vaccination, microbial fermentation, and pasteurization.",
        fact_zh: "巴斯德在疫苗、微生物發酵和巴氏消毒法方面做出了巨大貢獻。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question:
      "Which war was fought between the North and South regions of the United States (1861-1865)?",
    translation: "美國南北方之間發生的戰爭（1861-1865年）是什麼？",
    answers: [
      {
        text: "Revolutionary War",
        correct: false,
        translation: "獨立戰爭",
        fact: "The American Revolutionary War was fought between Great Britain and the Thirteen Colonies, which declared independence as the United States of America.",
        fact_zh: "美國獨立戰爭是北美十三個殖民地反抗英國統治的戰爭。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "War of 1812",
        correct: false,
        translation: "1812年戰爭",
        fact: "The War of 1812 was fought between the United States and Great Britain and its allies.",
        fact_zh: "1812年戰爭是美國與英國及其盟友之間的戰爭。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Vietnam War",
        correct: false,
        translation: "越南戰爭",
        fact: "The Vietnam War was fought in Southeast Asia from 1955 to 1975.",
        fact_zh: "越南戰爭於1955年至1975年在東南亞進行。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "American Civil War",
        correct: true,
        translation: "美國南北戰爭",
        fact: "The American Civil War was fought from 1861 to 1865 between the United States and the Confederate States of America, formed by states that had seceded from the Union.",
        fact_zh:
          "美國南北戰爭於1861年至1865年間在美國與從聯邦分裂出來的州組成的美利堅聯盟國之間進行。",
        correctFact:
          "The war's central issue was the legality of slavery, and its outcome led to the abolition of slavery and the preservation of the Union.",
        correctFact_zh:
          "戰爭的核心問題是奴隸制度的合法性，其結果導致了奴隸制度的廢除和聯邦的維護。電影《亂世佳人》的背景就是這場戰爭。",
      },
    ],
  },
  {
    question: "What is the capital of Canada?",
    translation: "加拿大的首都是什麼？",
    answers: [
      {
        text: "Toronto",
        correct: false,
        translation: "多倫多",
        fact: "Toronto is Canada's largest city and a major economic hub.",
        fact_zh: "多倫多是加拿大最大的城市和主要的經濟中心。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Vancouver",
        correct: false,
        translation: "溫哥華",
        fact: "Vancouver is a major city in British Columbia, known for its natural beauty.",
        fact_zh: "溫哥華是卑詩省的主要城市，以其自然美景聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Ottawa",
        correct: true,
        translation: "渥太華",
        fact: "Ottawa is the capital city of Canada, located on the Ottawa River in the eastern part of Southern Ontario.",
        fact_zh: "渥太華是加拿大的首都，位於安大略省南部東部的渥太華河畔。",
        correctFact:
          "It is home to many national institutions, including Parliament Hill and the National Gallery of Canada.",
        correctFact_zh:
          "它是許多國家機構的所在地，包括國會山莊和加拿大國家美術館。很多人會誤以為是多倫多或溫哥華呢！",
      },
      {
        text: "Montreal",
        correct: false,
        translation: "蒙特婁",
        fact: "Montreal is a major city in Quebec, known for its French-Canadian culture.",
        fact_zh: "蒙特婁是魁北克省的主要城市，以其法裔加拿大文化聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Which Italian city is famous for its canals?",
    translation: "哪個義大利城市以其運河聞名？",
    answers: [
      {
        text: "Rome",
        correct: false,
        translation: "羅馬",
        fact: "Rome is known for its ancient historical sites like the Colosseum.",
        fact_zh: "羅馬以其古老的歷史遺跡聞名，如羅馬競技場。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Florence",
        correct: false,
        translation: "佛羅倫斯",
        fact: "Florence is the birthplace of the Renaissance and rich in art heritage.",
        fact_zh: "佛羅倫斯是文藝復興的發源地，擁有豐富的藝術遺產。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Venice",
        correct: true,
        translation: "威尼斯",
        fact: "Venice is world-famous for its intricate canal system, gondolas, and unique architecture.",
        fact_zh: "威尼斯以其複雜的運河系統、貢多拉船和獨特的建築而聞名於世。",
        correctFact:
          "The city is built on 118 small islands in the Adriatic Sea lagoon and is often called the 'City of Water'.",
        correctFact_zh:
          "這座城市建在亞得里亞海潟湖中的118個小島上，被譽為「水都」。是個非常浪漫的城市！",
      },
      {
        text: "Naples",
        correct: false,
        translation: "拿坡里",
        fact: "Naples is the birthplace of pizza and is located near Mount Vesuvius.",
        fact_zh: "拿坡里是披薩的發源地，靠近維蘇威火山。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the chemical symbol for Sodium?",
    translation: "鈉的化學符號是什麼？",
    answers: [
      {
        text: "So",
        correct: false,
        translation: "So",
        fact: "This is not the standard chemical symbol for Sodium.",
        fact_zh: "這不是鈉的標準化學符號。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Na",
        correct: true,
        translation: "Na",
        fact: "Na is the chemical symbol for Sodium, derived from its Latin name 'Natrium'.",
        fact_zh: "Na 是鈉 (Sodium) 的化學符號，源自其拉丁名稱「Natrium」。",
        correctFact:
          "Sodium is a reactive metal and an essential electrolyte for humans, important for nerve function and fluid balance.",
        correctFact_zh:
          "鈉是一種活潑的金屬，也是人體必需的電解質，對於神經功能和體液平衡很重要。我們吃的鹽巴主要成分就是氯化鈉！",
      },
      {
        text: "Sd",
        correct: false,
        translation: "Sd",
        fact: "This is not a chemical symbol for a common element.",
        fact_zh: "這不是一個常見元素的化學符號。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "S",
        correct: false,
        translation: "S",
        fact: "S is the chemical symbol for Sulfur.",
        fact_zh: "S 是硫 (Sulfur) 的化學符號。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Who was the first President of the United States?",
    translation: "誰是美國第一任總統？",
    answers: [
      {
        text: "Thomas Jefferson",
        correct: false,
        translation: "湯瑪斯·傑佛遜",
        fact: "Thomas Jefferson was the third President of the United States and the principal author of the Declaration of Independence.",
        fact_zh:
          "湯瑪斯·傑佛遜是美國第三任總統，也是《獨立宣言》的主要起草人。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Abraham Lincoln",
        correct: false,
        translation: "亞伯拉罕·林肯",
        fact: "Abraham Lincoln was the sixteenth President of the United States, leading the country through the Civil War.",
        fact_zh: "亞伯拉罕·林肯是美國第十六任總統，領導國家度過了南北戰爭。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "George Washington",
        correct: true,
        translation: "喬治·華盛頓",
        fact: "George Washington was the first President of the United States and Commander-in-Chief of the Continental Army during the American Revolutionary War.",
        fact_zh:
          "喬治·華盛頓是美國第一任總統，也是美國獨立戰爭期間大陸軍的總司令。",
        correctFact:
          "He is revered as the 'Father of His Country' for his indispensable contributions to the founding of the United States.",
        correctFact_zh:
          "他被尊稱為「美國國父」，對美國的建立有著不可磨滅的貢獻。美金一塊錢上面就是他！",
      },
      {
        text: "John Adams",
        correct: false,
        translation: "約翰·亞當斯",
        fact: "John Adams was the second President of the United States.",
        fact_zh: "約翰·亞當斯是美國第二任總統。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Which country gifted the Statue of Liberty to the USA?",
    translation: "哪個國家將自由女神像贈送給美國？",
    answers: [
      {
        text: "United Kingdom",
        correct: false,
        translation: "英國",
        fact: "The USA was once a British colony before gaining independence.",
        fact_zh: "美國曾是英國的殖民地，後來獨立。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "France",
        correct: true,
        translation: "法國",
        fact: "The Statue of Liberty was a gift from the people of France to the people of the United States and was dedicated in 1886.",
        fact_zh: "自由女神像是法國人民贈送給美國人民的禮物，於1886年揭幕。",
        correctFact:
          "The statue symbolizes freedom and democracy and is a testament to the friendship between the two nations. Its designer also contributed to the Eiffel Tower.",
        correctFact_zh:
          "這座雕像象徵著自由和民主，是美法兩國友誼的見證。設計者也參與了艾菲爾鐵塔的設計喔！",
      },
      {
        text: "Spain",
        correct: false,
        translation: "西班牙",
        fact: "Spain was one of the major colonial powers in the Americas.",
        fact_zh: "西班牙曾是美洲主要的殖民強國之一。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Germany",
        correct: false,
        translation: "德國",
        fact: "German immigrants made significant contributions to the development of the United States.",
        fact_zh: "德國移民對美國的發展有重要貢獻。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the main ingredient in traditional Japanese miso soup?",
    translation: "傳統日式味噌湯的主要成分是什麼？",
    answers: [
      {
        text: "Soy sauce",
        correct: false,
        translation: "醬油",
        fact: "Soy sauce is a common seasoning in Japanese cuisine but not the primary base of miso soup.",
        fact_zh: "醬油是日本料理中常用的調味料，但不是味噌湯的主要成分。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Miso paste",
        correct: true,
        translation: "味噌醬",
        fact: "Miso paste, made from fermented soybeans, is the essential ingredient that gives miso soup its characteristic flavor.",
        fact_zh: "味噌醬是由發酵的大豆製成的糊狀物，是味噌湯的靈魂。",
        correctFact:
          "Miso soup is a traditional Japanese soup that often includes other ingredients like tofu, seaweed (wakame), and green onions.",
        correctFact_zh:
          "味噌湯是日本的傳統湯品，通常還會加入豆腐、海帶芽和蔥等配料。在台灣的日式料理店也很常見！",
      },
      {
        text: "Tofu",
        correct: false,
        translation: "豆腐",
        fact: "Tofu is a common ingredient in miso soup but not its main flavoring base.",
        fact_zh: "豆腐是味噌湯中常見的配料，但不是主要的調味基礎。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Seaweed",
        correct: false,
        translation: "海帶芽",
        fact: "Seaweed (often wakame) is also a common ingredient in miso soup.",
        fact_zh: "海帶芽也是味噌湯中常見的配料。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question:
      "Which is the largest moon of Saturn, known for its dense atmosphere?",
    translation: "土星最大的衛星是哪個，以其濃厚的大氣層聞名？",
    answers: [
      {
        text: "Europa",
        correct: false,
        translation: "歐羅巴 (Europa)",
        fact: "Europa is a moon of Jupiter, thought to have a liquid water ocean beneath its icy surface.",
        fact_zh: "歐羅巴是木星的衛星，被認為其冰層下可能有液態水海洋。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Ganymede",
        correct: false,
        translation: "蓋尼米德 (Ganymede)",
        fact: "Ganymede is Jupiter's largest moon and the largest moon in the solar system.",
        fact_zh: "蓋尼米德是木星最大的衛星，也是太陽系中最大的衛星。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Titan",
        correct: true,
        translation: "泰坦 (Titan)",
        fact: "Titan is Saturn's largest moon and the only moon in the solar system with a dense atmosphere and surface liquid.",
        fact_zh:
          "泰坦是土星最大的衛星，也是太陽系中唯一擁有濃厚大氣層和地表液體的衛星。",
        correctFact:
          "Titan's atmosphere is primarily nitrogen, and it has lakes and rivers of methane and ethane on its surface.",
        correctFact_zh:
          "泰坦的大氣主要由氮氣組成，地表有甲烷和乙烷構成的湖泊和河流，是個很特別的星體！",
      },
      {
        text: "Io",
        correct: false,
        translation: "伊奧 (Io)",
        fact: "Io is a moon of Jupiter known for its active volcanism.",
        fact_zh: "伊奧是木星的衛星，以其活躍的火山活動聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "In which sport is the term 'love' used to mean a score of zero?",
    translation: "在哪項運動中，「love」這個詞被用來表示零分？",
    answers: [
      {
        text: "Basketball",
        correct: false,
        translation: "籃球",
        fact: "The term 'love' is not used for scoring in basketball.",
        fact_zh: "籃球比賽中沒有用「love」來計分。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Soccer (Football)",
        correct: false,
        translation: "足球",
        fact: "The term 'love' is not used for scoring in soccer.",
        fact_zh: "足球比賽中也沒有用「love」來計分。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Tennis",
        correct: true,
        translation: "網球",
        fact: "In tennis, 'love' is used to mean a score of zero for a player or side.",
        fact_zh: "在網球比賽中，「love」用來表示一方得零分。",
        correctFact:
          "The origin of this usage is thought to come from the French word 'l'oeuf' (egg), because an egg resembles the numeral zero.",
        correctFact_zh:
          "這個用法據說源自法語中的「l'oeuf」（蛋），因為蛋的形狀像數字零。是不是很有趣的說法！",
      },
      {
        text: "Golf",
        correct: false,
        translation: "高爾夫球",
        fact: "Golf has its own unique scoring terms like bogey, par, etc.",
        fact_zh: "高爾夫球有其獨特的計分方式，如柏忌、帕等。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the name of the fictional city where Batman operates?",
    translation: "蝙蝠俠活動的虛構城市名稱是什麼？",
    answers: [
      {
        text: "Metropolis",
        correct: false,
        translation: "大都會 (Metropolis)",
        fact: "Metropolis is the city where Superman operates.",
        fact_zh: "大都會是超人活動的城市。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Gotham City",
        correct: true,
        translation: "高譚市 (Gotham City)",
        fact: "Gotham City is the primary setting for Batman's crime-fighting activities, known for its dark and corrupt atmosphere.",
        fact_zh: "高譚市是蝙蝠俠打擊犯罪的主要地點，以其黑暗和腐敗的氛圍聞名。",
        correctFact:
          "Gotham City's design was inspired by New York City, but it also incorporates elements from other major American cities.",
        correctFact_zh:
          "高譚市的設計靈感來自紐約市，但也融合了其他美國大城市的元素。是個充滿罪惡但也很有魅力的城市！",
      },
      {
        text: "Star City",
        correct: false,
        translation: "星城 (Star City)",
        fact: "Star City is the city where Green Arrow operates.",
        fact_zh: "星城是綠箭俠活動的城市。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Central City",
        correct: false,
        translation: "中心城 (Central City)",
        fact: "Central City is the city where The Flash operates.",
        fact_zh: "中心城是閃電俠活動的城市。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Which ancient civilization built Machu Picchu?",
    translation: "哪個古文明建造了馬丘比丘？",
    answers: [
      {
        text: "Maya",
        correct: false,
        translation: "馬雅文明",
        fact: "The Maya civilization, known for its pyramids, astronomy, and complex calendar, was primarily located in Mesoamerica.",
        fact_zh:
          "馬雅文明以其金字塔、天文學和複雜的曆法聞名，主要分佈在中美洲。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Aztec",
        correct: false,
        translation: "阿茲特克文明",
        fact: "The Aztec civilization was an ancient civilization in central Mexico, known for its capital Tenochtitlan.",
        fact_zh: "阿茲特克文明是墨西哥中部的古文明，以其首都特諾奇提特蘭聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Inca",
        correct: true,
        translation: "印加文明",
        fact: "Machu Picchu is an ancient city built by the Inca Empire in the 15th century, located in the Andes Mountains of Peru.",
        fact_zh: "馬丘比丘是印加帝國在15世紀建造的古城，位於秘魯安地斯山脈中。",
        correctFact:
          "This 'Lost City of the Incas' is renowned for its sophisticated stone architecture and breathtaking mountain scenery, and is one of the New Seven Wonders of the World.",
        correctFact_zh:
          "這座「失落的印加城市」以其精湛的石造建築和壯麗的山景聞名於世，是世界新七大奇蹟之一。真是令人讚嘆的古蹟！",
      },
      {
        text: "Egyptian",
        correct: false,
        translation: "埃及文明",
        fact: "The ancient Egyptian civilization is known for its pyramids, pharaohs, and hieroglyphs.",
        fact_zh: "古埃及文明以其金字塔、法老和象形文字聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "How many strings does a standard violin have?",
    translation: "標準的小提琴有幾條弦？",
    answers: [
      {
        text: "Four",
        correct: true,
        translation: "四條",
        fact: "A standard violin has four strings, typically tuned to G, D, A, and E.",
        fact_zh: "標準的小提琴有四條弦，通常調音為 G、D、A、E。",
        correctFact:
          "The violin is one of the highest-pitched instruments in the string family, and its beautiful tone makes it prominent in classical music and various other genres.",
        correctFact_zh:
          "小提琴是弦樂器家族中音域最高的樂器之一，其優美的音色使其在古典樂和各種音樂類型中都佔有重要地位。拉小提琴的姿勢也很優雅！",
      },
      {
        text: "Five",
        correct: false,
        translation: "五條",
        fact: "Some specially designed electric violins or violas might have five strings.",
        fact_zh: "有些特殊設計的電小提琴或中提琴可能有五條弦。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Six",
        correct: false,
        translation: "六條",
        fact: "Guitars typically have six strings.",
        fact_zh: "吉他通常有六條弦。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Seven",
        correct: false,
        translation: "七條",
        fact: "Some specialized or historical string instruments might have seven strings.",
        fact_zh: "某些特殊或古老的弦樂器可能有七條弦。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the common name for the solidified lava from a volcano?",
    translation: "火山噴發後凝固的熔岩通常稱為什麼？",
    answers: [
      {
        text: "Magma",
        correct: false,
        translation: "岩漿 (Magma)",
        fact: "Magma is molten rock found beneath the Earth's surface.",
        fact_zh: "岩漿是位於地表下的熔融岩石。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Sediment",
        correct: false,
        translation: "沉積物 (Sediment)",
        fact: "Sediment is solid material produced by weathering and erosion.",
        fact_zh: "沉積物是由風化和侵蝕作用產生的固體物質。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Igneous rock",
        correct: true,
        translation: "火成岩 (Igneous rock)",
        fact: "Igneous rock is formed from the cooling and solidification of lava or magma.",
        fact_zh: "火成岩是由熔岩或岩漿冷卻凝固形成的岩石。",
        correctFact:
          "Igneous rocks are divided into volcanic (extrusive) and plutonic (intrusive) rocks; examples include basalt and granite.",
        correctFact_zh:
          "火成岩分為火山岩（噴出岩）和深成岩（侵入岩），例如玄武岩和花崗岩都是常見的火成岩。台灣的大屯火山群就有許多火成岩地形。",
      },
      {
        text: "Metamorphic rock",
        correct: false,
        translation: "變質岩 (Metamorphic rock)",
        fact: "Metamorphic rock is formed from other rocks under high temperature and pressure.",
        fact_zh: "變質岩是由其他岩石在高溫高壓下轉變而成。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Which of the following is a type of cloud?",
    translation: "下列何者是一種雲的類型？",
    answers: [
      {
        text: "Tornado",
        correct: false,
        translation: "龍捲風 (Tornado)",
        fact: "A tornado is a violent rotating column of air, often associated with thunderstorm clouds.",
        fact_zh: "龍捲風是一種強烈的旋轉氣柱，常與雷暴雲相伴。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Hurricane",
        correct: false,
        translation: "颶風 (Hurricane)",
        fact: "A hurricane is an intense tropical cyclone that occurs in the Atlantic Ocean and northeastern Pacific Ocean.",
        fact_zh: "颶風是發生在大西洋和東北太平洋的強烈熱帶氣旋。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Cumulus",
        correct: true,
        translation: "積雲 (Cumulus)",
        fact: "Cumulus clouds are common clouds that look like cotton balls and usually indicate fair weather.",
        fact_zh: "積雲是一種常見的雲，外觀像棉花團，通常表示天氣晴朗。",
        correctFact:
          "If cumulus clouds continue to develop, they can become cumulonimbus clouds, which bring rain. Afternoon thundershowers in summer are often associated with cumulonimbus clouds.",
        correctFact_zh:
          "積雲如果持續發展，也可能變成降雨的積雨雲。夏天午後常見的雷陣雨就跟積雨雲有關！",
      },
      {
        text: "Blizzard",
        correct: false,
        translation: "暴風雪 (Blizzard)",
        fact: "A blizzard is severe weather characterized by strong winds and heavy snow.",
        fact_zh: "暴風雪是伴隨強風和大雪的惡劣天氣。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question:
      "What is the name of the force that pulls objects towards the center of the Earth?",
    translation: "將物體拉向地球中心的力稱為什麼？",
    answers: [
      {
        text: "Magnetism",
        correct: false,
        translation: "磁力",
        fact: "Magnetism is the attractive or repulsive force produced between magnets or electric currents.",
        fact_zh: "磁力是磁鐵之間或電流之間產生的吸引或排斥力。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Friction",
        correct: false,
        translation: "摩擦力",
        fact: "Friction is the force that resists the relative motion of objects.",
        fact_zh: "摩擦力是阻礙物體相對運動的力。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Gravity",
        correct: true,
        translation: "重力",
        fact: "Gravity is the natural phenomenon by which all things with mass are brought toward (or gravitate toward) one another.",
        fact_zh: "重力是使有質量的物體相互吸引的自然現象。",
        correctFact:
          "Earth's gravity keeps us on the ground and also keeps the Moon in orbit around the Earth. The story of Newton discovering universal gravitation when an apple fell on his head is famous!",
        correctFact_zh:
          "地球的重力使我們能站在地面上，也使月球圍繞地球運行。牛頓被蘋果砸到頭才發現萬有引力，這個故事很有名！",
      },
      {
        text: "Centrifugal force",
        correct: false,
        translation: "離心力",
        fact: "Centrifugal force is an inertial force observed in a rotating frame of reference.",
        fact_zh: "離心力是在旋轉參考系中觀察到的慣性力。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Which country is known for originating pizza?",
    translation: "哪個國家被認為是披薩的發源地？",
    answers: [
      {
        text: "Greece",
        correct: false,
        translation: "希臘",
        fact: "Ancient Greeks had a custom of eating flatbreads similar to pizza.",
        fact_zh: "古希臘人有食用類似披薩的扁麵包的習慣。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Italy",
        correct: true,
        translation: "義大利",
        fact: "Modern pizza originated in the Naples region of Italy.",
        fact_zh: "現代披薩起源於義大利的拿坡里地區。",
        correctFact:
          "Traditional Neapolitan pizza is known for its simple ingredients (like tomatoes, mozzarella, basil) and thin, crispy crust. Pizza is now available worldwide with diverse toppings!",
        correctFact_zh:
          "傳統的拿坡里披薩以其簡單的配料（如番茄、莫札瑞拉起司、羅勒）和薄脆的餅皮聞名。現在全世界都吃得到披薩，口味也很多元！",
      },
      {
        text: "United States",
        correct: false,
        translation: "美國",
        fact: "The United States has contributed significantly to the popularization and innovation of pizza, developing many American styles.",
        fact_zh: "美國對披薩的普及和創新有很大貢獻，發展出許多美式風格的披薩。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "France",
        correct: false,
        translation: "法國",
        fact: "France has a savory tart similar to pizza called 'Pissaladière'.",
        fact_zh: "法國有類似披薩的鹹派，稱為「Pissaladière」。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
];
