var questions_en_level2_data = [
  {
    question: "What do you use to write on a blackboard?",
    translation: "你用什麼在黑板上寫字？",
    answers: [
      {
        text: "Pen",
        correct: false,
        translation: "原子筆",
        fact: "Pens are used for writing on paper.",
        fact_zh: "原子筆是用來在紙上寫字的。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Marker",
        correct: false,
        translation: "白板筆",
        fact: "Markers are used on whiteboards or other surfaces.",
        fact_zh: "白板筆是用在白板或其他光滑表面上的。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Crayon",
        correct: false,
        translation: "蠟筆",
        fact: "Crayons are typically used for drawing on paper.",
        fact_zh: "蠟筆通常是用來在紙上畫圖的。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Chalk",
        correct: true,
        translation: "粉筆",
        fact: "Chalk is a soft, white, porous sedimentary carbonate rock, used for writing on blackboards.",
        fact_zh:
          "粉筆是一種柔軟、白色、多孔的沉積碳酸鹽岩石，用於在黑板上書寫。",
        correctFact:
          "Blackboards were traditionally made of slate, and chalk is made primarily of calcium carbonate.",
        correctFact_zh:
          "傳統黑板是用石板製成的，而粉筆主要成分是碳酸鈣。現在很多學校改用白板，比較沒有粉筆灰了。",
      },
    ],
  },
  {
    question: "Which planet is closest to the Sun?",
    translation: "哪顆行星離太陽最近？",
    answers: [
      {
        text: "Venus",
        correct: false,
        translation: "金星",
        fact: "Venus is the second planet from the Sun, known for its extreme heat.",
        fact_zh: "金星是離太陽第二近的行星，以其極端高溫而聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Earth",
        correct: false,
        translation: "地球",
        fact: "Earth is the third planet from the Sun, our home planet.",
        fact_zh: "地球是離太陽第三近的行星，是我們的家。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Mercury",
        correct: true,
        translation: "水星",
        fact: "Mercury is the smallest planet in our solar system and the closest to the Sun.",
        fact_zh: "水星是太陽系中最小的行星，也是離太陽最近的行星。",
        correctFact:
          "Due to its proximity to the Sun, Mercury experiences extreme temperature variations between day and night.",
        correctFact_zh:
          "由於離太陽很近，水星的白天和夜晚溫差極大。真是「冰火五重天」的星球！",
      },
      {
        text: "Mars",
        correct: false,
        translation: "火星",
        fact: "Mars is the fourth planet from the Sun, known as the 'Red Planet'.",
        fact_zh: "火星是離太陽第四近的行星，被稱為「紅色星球」。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "If you mix yellow and blue paint, what color do you get?",
    translation: "如果混合黃色和藍色顏料，會得到什麼顏色？",
    answers: [
      {
        text: "Red",
        correct: false,
        translation: "紅色",
        fact: "Red is a primary color.",
        fact_zh: "紅色是一種三原色。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Green",
        correct: true,
        translation: "綠色",
        fact: "Mixing yellow and blue pigments creates green.",
        fact_zh: "混合黃色和藍色顏料會產生綠色。",
        correctFact:
          "Green is a secondary color in the subtractive color model used in painting.",
        correctFact_zh:
          "在繪畫中使用的減色法色彩模型中，綠色是二次色。這是美術課的基本常識喔！",
      },
      {
        text: "Orange",
        correct: false,
        translation: "橙色",
        fact: "Orange is made by mixing red and yellow.",
        fact_zh: "橙色是由紅色和黃色混合而成。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Purple",
        correct: false,
        translation: "紫色",
        fact: "Purple is made by mixing red and blue.",
        fact_zh: "紫色是由紅色和藍色混合而成。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question:
      "Which geometric shape has four equal sides and four right angles?",
    translation: "哪種幾何圖形有四條等長的邊和四個直角？",
    answers: [
      {
        text: "Circle",
        correct: false,
        translation: "圓形",
        fact: "A circle is a round shape with no straight sides.",
        fact_zh: "圓形是一個沒有直線邊的圓形圖形。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Triangle",
        correct: false,
        translation: "三角形",
        fact: "A triangle has three sides.",
        fact_zh: "三角形有三條邊。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Square",
        correct: true,
        translation: "正方形",
        fact: "A square is a quadrilateral with four equal sides and four right angles.",
        fact_zh: "正方形是一個有四條等長邊和四個直角的四邊形。",
        correctFact:
          "All squares are rectangles, but not all rectangles are squares.",
        correctFact_zh:
          "所有的正方形都是長方形，但並非所有的長方形都是正方形。就像台灣的刈包，一定是長方形的嗎？（開玩笑的）",
      },
      {
        text: "Rectangle",
        correct: false,
        translation: "長方形",
        fact: "A rectangle has four sides and four right angles, but only opposite sides are necessarily equal.",
        fact_zh: "長方形有四條邊和四個直角，但只有對邊必須相等。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Which planet is known as the Red Planet?",
    translation: "哪顆行星被稱為紅色星球？",
    answers: [
      {
        text: "Jupiter",
        correct: false,
        translation: "木星",
        fact: "Jupiter is the largest planet in our solar system.",
        fact_zh: "木星是太陽系中最大的行星。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Mars",
        correct: true,
        translation: "火星",
        fact: "Mars is known as the Red Planet due to the iron oxide (rust) on its surface.",
        fact_zh: "火星因其表面的氧化鐵（鐵鏽）而被稱為紅色星球。",
        correctFact: "Mars has two small moons, Phobos and Deimos.",
        correctFact_zh:
          "火星有兩顆小衛星，分別是火衛一 (Phobos) 和火衛二 (Deimos)。人類一直對移民火星充滿想像！",
      },
      {
        text: "Venus",
        correct: false,
        translation: "金星",
        fact: "Venus is often called Earth's 'sister planet' due to its similar size.",
        fact_zh: "金星因其大小與地球相似，常被稱為地球的「姊妹行星」。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Saturn",
        correct: false,
        translation: "土星",
        fact: "Saturn is famous for its prominent ring system.",
        fact_zh: "土星以其顯著的環系統而聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "In which sport would you perform a slam dunk?",
    translation: "在哪項運動中你會做出灌籃的動作？",
    answers: [
      {
        text: "Basketball",
        correct: true,
        translation: "籃球",
        fact: "A slam dunk is a type of shot in basketball where a player jumps and forces the ball downward through the hoop.",
        fact_zh: "灌籃是籃球中的一種投籃方式，球員跳起並將球用力扣入籃框。",
        correctFact:
          "The first recorded slam dunk in a game was by Bob Kurland in 1944, though it wasn't called a 'slam dunk' at the time.",
        correctFact_zh:
          "有記錄以來的第一個比賽中的灌籃是由鮑伯·庫蘭在1944年完成的，不過當時還不叫做「灌籃」。台灣職籃也有很多精彩的灌籃喔！",
      },
      {
        text: "Soccer (Football)",
        correct: false,
        translation: "足球",
        fact: "Soccer involves kicking a ball into a goal.",
        fact_zh: "足球是用腳將球踢進球門。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Tennis",
        correct: false,
        translation: "網球",
        fact: "Tennis involves hitting a ball over a net with a racket.",
        fact_zh: "網球是用球拍將球擊過網。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Golf",
        correct: false,
        translation: "高爾夫球",
        fact: "Golf involves hitting a small ball into a series of holes.",
        fact_zh: "高爾夫球是將小球打入一系列的球洞中。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the chemical symbol for water?",
    translation: "水的化學符號是什麼？",
    answers: [
      {
        text: "O2",
        correct: false,
        translation: "O₂",
        fact: "O2 is the chemical symbol for oxygen gas.",
        fact_zh: "O₂ 是氧氣的化學符號。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "CO2",
        correct: false,
        translation: "CO₂",
        fact: "CO2 is the chemical symbol for carbon dioxide.",
        fact_zh: "CO₂ 是二氧化碳的化學符號。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "H2O",
        correct: true,
        translation: "H₂O",
        fact: "H2O is the chemical formula for water, indicating two hydrogen atoms and one oxygen atom.",
        fact_zh: "H₂O 是水的化學式，表示兩個氫原子和一個氧原子。",
        correctFact:
          "Water is essential for all known forms of life and covers about 71% of Earth's surface.",
        correctFact_zh:
          "水對所有已知的生命形式都至關重要，約佔地球表面的71%。台灣雖然常下雨，但也要節約用水！",
      },
      {
        text: "NaCl",
        correct: false,
        translation: "NaCl",
        fact: "NaCl is the chemical symbol for sodium chloride, or table salt.",
        fact_zh: "NaCl 是氯化鈉（食鹽）的化學符號。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is a young cow called?",
    translation: "小牛的英文是什麼？",
    answers: [
      {
        text: "Foal",
        correct: false,
        translation: "Foal (幼馬)",
        fact: "A foal is a young horse.",
        fact_zh: "Foal 是指幼馬。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Chick",
        correct: false,
        translation: "Chick (小雞)",
        fact: "A chick is a young chicken.",
        fact_zh: "Chick 是指幼雞。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Calf",
        correct: true,
        translation: "Calf (小牛)",
        fact: "A young cow is called a calf.",
        fact_zh: "幼牛的英文是 Calf。",
        correctFact:
          "Calves are typically weaned from their mothers between 6 to 8 months of age.",
        correctFact_zh:
          "小牛通常在6到8個月大的時候斷奶。在牧場看到小牛很療癒呢！",
      },
      {
        text: "Lamb",
        correct: false,
        translation: "Lamb (小羊)",
        fact: "A lamb is a young sheep.",
        fact_zh: "Lamb 是指幼羊。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the largest land animal?",
    translation: "陸地上體型最大的動物是什麼？",
    answers: [
      {
        text: "Giraffe",
        correct: false,
        translation: "長頸鹿",
        fact: "Giraffes are the tallest mammals.",
        fact_zh: "長頸鹿是最高的哺乳動物。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Elephant",
        correct: true,
        translation: "大象",
        fact: "The African bush elephant is the largest living land animal by mass.",
        fact_zh: "非洲草原象是現存體重最大的陸地動物。",
        correctFact:
          "Elephants are known for their long trunks, large ears, and tusks, and are highly intelligent and social animals.",
        correctFact_zh:
          "大象以其長鼻子、大耳朵和象牙而聞名，是高度聰明和群居的動物。動物園裡的大象總是人氣王！",
      },
      {
        text: "Rhinoceros",
        correct: false,
        translation: "犀牛",
        fact: "Rhinoceroses are large, herbivorous mammals known for their horns.",
        fact_zh: "犀牛是大型食草哺乳動物，以其角而聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Hippopotamus",
        correct: false,
        translation: "河馬",
        fact: "Hippopotamuses are large, semi-aquatic mammals native to sub-Saharan Africa.",
        fact_zh: "河馬是大型半水生哺乳動物，原產於撒哈拉以南非洲地區。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question:
      "What is the process by which plants make their own food using sunlight?",
    translation: "植物利用陽光製造自身養分的過程稱為什麼？",
    answers: [
      {
        text: "Respiration",
        correct: false,
        translation: "呼吸作用",
        fact: "Respiration is the process by which organisms convert nutrients into energy.",
        fact_zh: "呼吸作用是生物體將養分轉化為能量的過程。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Photosynthesis",
        correct: true,
        translation: "光合作用",
        fact: "Photosynthesis is the process used by plants, algae, and cyanobacteria to convert light energy into chemical energy.",
        fact_zh: "光合作用是植物、藻類和藍綠菌等用來將光能轉化為化學能的過程。",
        correctFact:
          "This process primarily uses sunlight, water, and carbon dioxide to create glucose (sugar) and oxygen.",
        correctFact_zh:
          "這個過程主要利用陽光、水和二氧化碳來製造葡萄糖（糖）和氧氣。可以說是植物的「太陽能廚房」。",
      },
      {
        text: "Germination",
        correct: false,
        translation: "發芽",
        fact: "Germination is the process by which an organism grows from a seed or spore.",
        fact_zh: "發芽是生物體從種子或孢子生長的過程。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Pollination",
        correct: false,
        translation: "授粉",
        fact: "Pollination is the transfer of pollen from an anther to a stigma in flowering plants.",
        fact_zh: "授粉是開花植物中花粉從花藥轉移到柱頭的過程。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the tallest mammal on Earth?",
    translation: "地球上最高的哺乳動物是什麼？",
    answers: [
      {
        text: "Elephant",
        correct: false,
        translation: "大象",
        fact: "Elephants are the largest land animals by mass.",
        fact_zh: "依重量來說，大象是陸地上最大的動物。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Whale",
        correct: false,
        translation: "鯨魚",
        fact: "Whales are the largest mammals overall, but they live in water.",
        fact_zh: "鯨魚是體型最大的哺乳動物，但牠們生活在水中。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Giraffe",
        correct: true,
        translation: "長頸鹿",
        fact: "Giraffes are the tallest living terrestrial animals, known for their extremely long necks and legs.",
        fact_zh: "長頸鹿是現存最高的陸地動物，以其極長的脖子和腿而聞名。",
        correctFact:
          "A giraffe's neck alone can be over 6 feet (1.8 meters) long.",
        correctFact_zh:
          "光是長頸鹿的脖子就可以超過1.8公尺長。真是「高人一等」啊！",
      },
      {
        text: "Rhino",
        correct: false,
        translation: "犀牛",
        fact: "Rhinos are large, herbivorous mammals.",
        fact_zh: "犀牛是大型食草哺乳動物。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "In which country are the Pyramids of Giza located?",
    translation: "吉薩金字塔位於哪個國家？",
    answers: [
      {
        text: "Greece",
        correct: false,
        translation: "希臘",
        fact: "Greece is home to ancient ruins like the Parthenon.",
        fact_zh: "希臘擁有帕德嫩神廟等古老遺跡。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Egypt",
        correct: true,
        translation: "埃及",
        fact: "The Pyramids of Giza are ancient pyramid complexes in Egypt, including the Great Pyramid of Giza, the Pyramid of Khafre, and the Pyramid of Menkaure.",
        fact_zh:
          "吉薩金字塔是位於埃及的古老金字塔群，包括吉薩大金字塔、卡夫拉金字塔和孟卡拉金字塔。",
        correctFact:
          "The Great Pyramid of Giza is the oldest and largest of the three pyramids in the Giza Necropolis and is the only one of the Seven Wonders of the Ancient World still largely intact.",
        correctFact_zh:
          "吉薩大金字塔是吉薩墓地中三座金字塔中最古老、最大的一座，也是古代世界七大奇蹟中唯一基本完好的一座。真是人類文明的瑰寶！",
      },
      {
        text: "Mexico",
        correct: false,
        translation: "墨西哥",
        fact: "Mexico has ancient Mayan and Aztec pyramids.",
        fact_zh: "墨西哥擁有古老的馬雅和阿茲特克金字塔。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Italy",
        correct: false,
        translation: "義大利",
        fact: "Italy is known for Roman ruins like the Colosseum.",
        fact_zh: "義大利以羅馬競技場等羅馬遺跡而聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "How many sides does a hexagon have?",
    translation: "六邊形有幾條邊？",
    answers: [
      {
        text: "5",
        correct: false,
        translation: "5條",
        fact: "A shape with 5 sides is a pentagon.",
        fact_zh: "有5條邊的圖形是五邊形。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "6",
        correct: true,
        translation: "6條",
        fact: "A hexagon is a polygon with six sides and six angles.",
        fact_zh: "六邊形是一個有六條邊和六個角的多邊形。",
        correctFact:
          "Honeycomb cells made by bees are a classic example of natural hexagonal structures, known for their efficiency in packing.",
        correctFact_zh:
          "蜜蜂製造的蜂巢是自然界六邊形結構的典型例子，以其高效的堆疊方式而聞名。大自然真是充滿智慧！",
      },
      {
        text: "7",
        correct: false,
        translation: "7條",
        fact: "A shape with 7 sides is a heptagon.",
        fact_zh: "有7條邊的圖形是七邊形。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "8",
        correct: false,
        translation: "8條",
        fact: "A shape with 8 sides is an octagon.",
        fact_zh: "有8條邊的圖形是八邊形。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the name of the galaxy that contains our Solar System?",
    translation: "包含我們太陽系的星系名稱是什麼？",
    answers: [
      {
        text: "Andromeda",
        correct: false,
        translation: "仙女座星系",
        fact: "Andromeda is the closest large spiral galaxy to the Milky Way.",
        fact_zh: "仙女座星系是離銀河系最近的大型螺旋星系。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Triangulum",
        correct: false,
        translation: "三角座星系",
        fact: "Triangulum is a small spiral galaxy that is part of the Local Group.",
        fact_zh: "三角座星系是一個小型螺旋星系，是本星系群的一部分。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Milky Way",
        correct: true,
        translation: "銀河系",
        fact: "Our solar system is located in the Milky Way Galaxy, a barred spiral galaxy.",
        fact_zh: "我們的太陽系位於銀河系中，這是一個棒旋星系。",
        correctFact:
          "The Milky Way contains an estimated 100-400 billion stars and is part of the Local Group of galaxies.",
        correctFact_zh:
          "銀河系估計包含1000億到4000億顆恆星，是本星系群的一部分。我們就住在這個「宇宙中的家」！",
      },
      {
        text: "Sombrero",
        correct: false,
        translation: "草帽星系",
        fact: "The Sombrero Galaxy is a spiral galaxy in the constellation Virgo.",
        fact_zh: "草帽星系是位於室女座的一個螺旋星系。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Which ocean separates Europe and North America?",
    translation: "哪個海洋分隔了歐洲和北美洲？",
    answers: [
      {
        text: "Indian Ocean",
        correct: false,
        translation: "印度洋",
        fact: "The Indian Ocean is the third largest ocean, bordering India and Australia.",
        fact_zh: "印度洋是第三大洋，與印度和澳洲接壤。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Pacific Ocean",
        correct: false,
        translation: "太平洋",
        fact: "The Pacific Ocean is the largest and deepest of Earth's oceanic divisions.",
        fact_zh: "太平洋是地球上最大且最深的海洋。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Arctic Ocean",
        correct: false,
        translation: "北極海",
        fact: "The Arctic Ocean surrounds the North Pole.",
        fact_zh: "北極海環繞著北極。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Atlantic Ocean",
        correct: true,
        translation: "大西洋",
        fact: "The Atlantic Ocean separates the continents of Europe and Africa from North and South America.",
        fact_zh: "大西洋分隔了歐洲、非洲與北美洲、南美洲。",
        correctFact:
          "It is the second-largest ocean basin on Earth, covering approximately 20% of the Earth's surface.",
        correctFact_zh:
          "它是地球上第二大洋盆，約佔地球表面積的20%。鐵達尼號就是沉沒在大西洋。",
      },
    ],
  },
  {
    question: "What is the freezing point of water in Celsius?",
    translation: "水的冰點是攝氏幾度？",
    answers: [
      {
        text: "100°C",
        correct: false,
        translation: "攝氏100度",
        fact: "100°C is the boiling point of water at standard atmospheric pressure.",
        fact_zh: "攝氏100度是標準大氣壓力下水的沸點。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "0°C",
        correct: true,
        translation: "攝氏0度",
        fact: "Water freezes at 0 degrees Celsius (32 degrees Fahrenheit) at standard atmospheric pressure.",
        fact_zh: "在標準大氣壓力下，水在攝氏0度（華氏32度）結冰。",
        correctFact:
          "This temperature is a key reference point in the Celsius scale, which is widely used globally.",
        correctFact_zh:
          "這個溫度是攝氏溫標的一個關鍵參考點，在全球廣泛使用。台灣高山冬天有機會看到結冰喔！",
      },
      {
        text: "-10°C",
        correct: false,
        translation: "攝氏零下10度",
        fact: "-10°C is below the freezing point of water.",
        fact_zh: "攝氏零下10度低於水的冰點。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "50°C",
        correct: false,
        translation: "攝氏50度",
        fact: "50°C is a warm temperature, well above freezing.",
        fact_zh: "攝氏50度是溫暖的溫度，遠高於冰點。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Which famous leaning tower is located in Italy?",
    translation: "哪座著名的斜塔位於義大利？",
    answers: [
      {
        text: "Leaning Tower of Pisa",
        correct: true,
        translation: "比薩斜塔",
        fact: "The Leaning Tower of Pisa is the campanile, or bell tower, of the Pisa Cathedral, famous for its unintended tilt.",
        fact_zh: "比薩斜塔是比薩大教堂的鐘樓，以其意外的傾斜而聞名。",
        correctFact:
          "Its tilt was caused by an inadequate foundation on soft ground, which began during its construction in the 12th century.",
        correctFact_zh:
          "它的傾斜是由於建在鬆軟地基上且地基不足所致，從12世紀開始建造時就開始傾斜了。是個「歪」打正著的世界奇觀！",
      },
      {
        text: "Eiffel Tower",
        correct: false,
        translation: "艾菲爾鐵塔",
        fact: "The Eiffel Tower is in Paris, France.",
        fact_zh: "艾菲爾鐵塔位於法國巴黎。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Big Ben",
        correct: false,
        translation: "大笨鐘",
        fact: "Big Ben is the nickname for the Great Bell of the clock at the north end of the Palace of Westminster in London, England.",
        fact_zh: "大笨鐘是倫敦西敏宮北端鐘樓大鐘的暱稱。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Tower of London",
        correct: false,
        translation: "倫敦塔",
        fact: "The Tower of London is a historic castle on the north bank of the River Thames in central London.",
        fact_zh: "倫敦塔是位於倫敦市中心泰晤士河北岸的一座歷史悠久的城堡。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Who is the author of the Harry Potter book series?",
    translation: "《哈利波特》系列叢書的作者是誰？",
    answers: [
      {
        text: "J.R.R. Tolkien",
        correct: false,
        translation: "J.R.R. 托爾金",
        fact: "J.R.R. Tolkien wrote 'The Lord of the Rings'.",
        fact_zh: "J.R.R. 托爾金寫了《魔戒》。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "George R.R. Martin",
        correct: false,
        translation: "喬治·R·R·馬丁",
        fact: "George R.R. Martin wrote 'A Song of Ice and Fire' (Game of Thrones).",
        fact_zh: "喬治·R·R·馬丁寫了《冰與火之歌》（權力遊戲）。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "J.K. Rowling",
        correct: true,
        translation: "J.K. 羅琳",
        fact: "J.K. Rowling is the British author who created the Harry Potter fantasy series.",
        fact_zh: "J.K. 羅琳是創作出《哈利波特》奇幻系列的英國作家。",
        correctFact:
          "The Harry Potter series became a global phenomenon, selling over 500 million copies worldwide and inspiring a major film franchise.",
        correctFact_zh:
          "《哈利波特》系列風靡全球，全球銷量超過5億冊，並催生了主要的電影系列。陪伴了許多人的童年！",
      },
      {
        text: "Suzanne Collins",
        correct: false,
        translation: "蘇珊·柯林斯",
        fact: "Suzanne Collins wrote 'The Hunger Games' series.",
        fact_zh: "蘇珊·柯林斯寫了《飢餓遊戲》系列。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Who is known as the 'King of Pop'?",
    translation: "誰被稱為「流行音樂之王」？",
    answers: [
      {
        text: "Elvis Presley",
        correct: false,
        translation: "貓王 (Elvis Presley)",
        fact: "Elvis Presley is known as the 'King of Rock and Roll'.",
        fact_zh: "貓王被稱為「搖滾樂之王」。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Michael Jackson",
        correct: true,
        translation: "麥可·傑克森 (Michael Jackson)",
        fact: "Michael Jackson was an American singer, songwriter, and dancer, widely regarded as the 'King of Pop'.",
        fact_zh:
          "麥可·傑克森是美國歌手、詞曲作者和舞者，被廣泛認為是「流行音樂之王」。",
        correctFact:
          "His contributions to music, dance, and fashion, along with his publicized personal life, made him a global figure in popular culture for over four decades.",
        correctFact_zh:
          "他對音樂、舞蹈和時尚的貢獻，以及他公開的個人生活，使他在四十多年的時間裡成為流行文化的全球性人物。他的月球漫步超經典！",
      },
      {
        text: "Madonna",
        correct: false,
        translation: "瑪丹娜 (Madonna)",
        fact: "Madonna is known as the 'Queen of Pop'.",
        fact_zh: "瑪丹娜被稱為「流行音樂女王」。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Prince",
        correct: false,
        translation: "王子 (Prince)",
        fact: "Prince was an American singer-songwriter, multi-instrumentalist, record producer, and actor.",
        fact_zh: "王子是美國歌手、詞曲作者、多樂器演奏家、唱片製作人和演員。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "In which city would you find the Colosseum?",
    translation: "你可以在哪個城市找到羅馬競技場？",
    answers: [
      {
        text: "Paris",
        correct: false,
        translation: "巴黎",
        fact: "Paris is home to the Eiffel Tower.",
        fact_zh: "巴黎有艾菲爾鐵塔。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "London",
        correct: false,
        translation: "倫敦",
        fact: "London is home to Big Ben and the Tower of London.",
        fact_zh: "倫敦有大笨鐘和倫敦塔。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Rome",
        correct: true,
        translation: "羅馬",
        fact: "The Colosseum is an ancient amphitheatre in the center of Rome, Italy.",
        fact_zh: "羅馬競技場是位於義大利羅馬市中心的一座古老圓形劇場。",
        correctFact:
          "It is the largest ancient amphitheatre ever built, and is still the largest standing amphitheatre in the world, despite its age.",
        correctFact_zh:
          "它是迄今為止建造的最大的古羅馬圓形劇場，儘管年代久遠，至今仍是世界上最大的現存圓形劇場。神鬼戰士的場景歷歷在目！",
      },
      {
        text: "Athens",
        correct: false,
        translation: "雅典",
        fact: "Athens is home to the Acropolis and Parthenon.",
        fact_zh: "雅典有雅典衛城和帕德嫩神廟。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Which country is famous for its tulips and windmills?",
    translation: "哪個國家以其鬱金香和風車聞名？",
    answers: [
      {
        text: "Germany",
        correct: false,
        translation: "德國",
        fact: "Germany is known for its beer, sausages, and cars.",
        fact_zh: "德國以啤酒、香腸和汽車聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "France",
        correct: false,
        translation: "法國",
        fact: "France is known for its wine, cheese, and the Eiffel Tower.",
        fact_zh: "法國以葡萄酒、起司和艾菲爾鐵塔聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Netherlands",
        correct: true,
        translation: "荷蘭",
        fact: "The Netherlands is world-renowned for its beautiful tulip fields and historic windmills.",
        fact_zh: "荷蘭以其美麗的鬱金香花田和歷史悠久的風車而聞名於世。",
        correctFact:
          "Windmills played a crucial role in Dutch history for land reclamation by pumping water, and tulips are a significant export flower for the country.",
        correctFact_zh:
          "風車在荷蘭歷史上扮演了抽水造陸的重要角色，而鬱金香則是該國重要的出口花卉。有機會一定要去看看！",
      },
      {
        text: "Belgium",
        correct: false,
        translation: "比利時",
        fact: "Belgium is known for its chocolate, beer, and waffles.",
        fact_zh: "比利時以巧克力、啤酒和鬆餅聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the main language spoken in Spain?",
    translation: "西班牙的主要語言是什麼？",
    answers: [
      {
        text: "Portuguese",
        correct: false,
        translation: "葡萄牙語",
        fact: "Portuguese is the main language of Portugal and Brazil.",
        fact_zh: "葡萄牙語是葡萄牙和巴西的主要語言。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Spanish",
        correct: true,
        translation: "西班牙語",
        fact: "Spanish is the official language of Spain and the second most natively spoken language in the world.",
        fact_zh: "西班牙語是西班牙的官方語言，也是世界上使用人數第二多的母語。",
        correctFact:
          "Besides Spain, most countries in Latin America also use Spanish.",
        correctFact_zh:
          "除了西班牙，拉丁美洲大部分國家也使用西班牙語。學會西班牙語可以跟很多人溝通喔！",
      },
      {
        text: "Italian",
        correct: false,
        translation: "義大利語",
        fact: "Italian is the main language of Italy.",
        fact_zh: "義大利語是義大利的主要語言。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "French",
        correct: false,
        translation: "法語",
        fact: "French is the official language of France and many other countries.",
        fact_zh: "法語是法國和許多其他國家的官方語言。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Which of these is a primary color?",
    translation: "下列何者是三原色之一？",
    answers: [
      {
        text: "Green",
        correct: false,
        translation: "綠色",
        fact: "Green is a secondary color, made by mixing blue and yellow.",
        fact_zh: "綠色是由藍色和黃色混合而成的二次色。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Orange",
        correct: false,
        translation: "橙色",
        fact: "Orange is a secondary color, made by mixing red and yellow.",
        fact_zh: "橙色是由紅色和黃色混合而成的二次色。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Blue",
        correct: true,
        translation: "藍色",
        fact: "Blue is one of the primary colors and cannot be made by mixing other colors.",
        fact_zh: "藍色是三原色之一，無法由其他顏色混合而成。",
        correctFact:
          "In the additive primary colors (RGB), blue is one; in the subtractive primary colors (CMY or RYB), blue is also a base color.",
        correctFact_zh:
          "在光學三原色 (RGB) 中，藍色是其中之一；在顏料三原色 (CMY 或 RYB) 中，藍色也是基礎顏色。美術課一定會教！",
      },
      {
        text: "Purple",
        correct: false,
        translation: "紫色",
        fact: "Purple is a secondary color, made by mixing red and blue.",
        fact_zh: "紫色是由紅色和藍色混合而成的二次色。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "How many continents are there (commonly accepted model)?",
    translation: "世界上普遍公認有幾大洲？",
    answers: [
      {
        text: "5",
        correct: false,
        translation: "五大洲",
        fact: "Some models consider Eurasia as one continent or exclude Antarctica.",
        fact_zh: "某些模型將歐亞大陸視為一個洲，或不計南極洲。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "6",
        correct: false,
        translation: "六大洲",
        fact: "Some models consider North and South America as one American continent.",
        fact_zh: "某些模型將北美和南美視為一個美洲大陸。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "7",
        correct: true,
        translation: "七大洲",
        fact: "The most widely accepted model is seven continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia.",
        fact_zh:
          "最廣為接受的模型是七大洲：亞洲、非洲、北美洲、南美洲、南極洲、歐洲和澳洲。",
        correctFact:
          "This model is widely used and taught in English-speaking countries and Western Europe.",
        correctFact_zh:
          "這個模型在英語系國家和西歐被廣泛使用和教導。台灣的地理課本也是這樣教的！",
      },
      {
        text: "8",
        correct: false,
        translation: "八大洲",
        fact: "There is no widely accepted eight-continent model.",
        fact_zh: "目前沒有廣泛接受的八大洲模型。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the capital of Italy?",
    translation: "義大利的首都是什麼？",
    answers: [
      {
        text: "Venice",
        correct: false,
        translation: "威尼斯",
        fact: "Venice is famous for its canals and gondolas.",
        fact_zh: "威尼斯以其運河和貢多拉船聞名。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Milan",
        correct: false,
        translation: "米蘭",
        fact: "Milan is Italy's fashion and financial hub.",
        fact_zh: "米蘭是義大利的時尚和金融中心。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Rome",
        correct: true,
        translation: "羅馬",
        fact: "Rome is the capital of Italy, rich in history and ancient monuments.",
        fact_zh: "羅馬是義大利的首都，擁有悠久的歷史和許多古蹟。",
        correctFact:
          "Also known as the 'Eternal City', Rome boasts famous landmarks like the Colosseum and the Pantheon.",
        correctFact_zh:
          "羅馬也被稱為「永恆之城」，擁有羅馬競技場、萬神殿等著名景點。是個充滿歷史感的城市！",
      },
      {
        text: "Florence",
        correct: false,
        translation: "佛羅倫斯",
        fact: "Florence is the birthplace of the Renaissance.",
        fact_zh: "佛羅倫斯是文藝復興的發源地。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
];
