var questions_en_level1_data = [
  {
    question: "What is the color of the sky on a clear day?",
    translation: "晴朗的天空是什麼顏色？",
    answers: [
      {
        text: "Green",
        correct: false,
        translation: "綠色",
        fact: "Green is the color of grass and leaves.",
        fact_zh: "綠色是草和葉子的顏色。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Blue",
        correct: true,
        translation: "藍色",
        fact: "The sky appears blue due to Rayleigh scattering of sunlight by the Earth's atmosphere.",
        fact_zh: "由於地球大氣層對陽光的瑞利散射，天空呈現藍色。",
        correctFact:
          "Rayleigh scattering is why shorter wavelengths of light, like blue and violet, are scattered more efficiently than longer wavelengths, like red and yellow.",
        correctFact_zh:
          "瑞利散射解釋了為什麼像藍色和紫色這樣的短波長光線，比像紅色和黃色這樣的長波長光線更容易被散射。這跟我們抬頭看到藍天很有關係喔！",
      },
      {
        text: "Red",
        correct: false,
        translation: "紅色",
        fact: "Red is often seen during sunsets or sunrises.",
        fact_zh: "紅色通常在日落或日出時出現。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Yellow",
        correct: false,
        translation: "黃色",
        fact: "Yellow is the color of the sun itself.",
        fact_zh: "黃色是太陽本身的顏色。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "How many legs does a spider typically have?",
    translation: "蜘蛛通常有幾隻腳？",
    answers: [
      {
        text: "6",
        correct: false,
        translation: "6隻",
        fact: "Insects typically have 6 legs.",
        fact_zh: "昆蟲通常有6隻腳，例如螞蟻。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "8",
        correct: true,
        translation: "8隻",
        fact: "Spiders are arachnids, not insects, and are characterized by having eight legs.",
        fact_zh: "蜘蛛是蛛形綱動物，不是昆蟲，牠們的特徵是有八隻腳。",
        correctFact:
          "Arachnids also include scorpions, ticks, and mites, all sharing the characteristic of eight legs.",
        correctFact_zh:
          "蛛形綱動物還包括蠍子、壁蝨和蟎蟲，牠們都有八隻腳這個共同特徵。下次看到八隻腳的，就知道牠不是普通昆蟲啦！",
      },
      {
        text: "10",
        correct: false,
        translation: "10隻",
        fact: "Some crustaceans, like crabs, have 10 legs.",
        fact_zh: "有些甲殼類動物，像是螃蟹，有10隻腳。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "4",
        correct: false,
        translation: "4隻",
        fact: "Most mammals, like dogs and cats, have 4 legs.",
        fact_zh: "大部分哺乳動物，像是狗和貓，有4隻腳。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Which animal is known as the 'King of the Jungle'?",
    translation: "哪種動物被稱為「森林之王」？",
    answers: [
      {
        text: "Tiger",
        correct: false,
        translation: "老虎",
        fact: "Tigers are the largest cat species and powerful predators.",
        fact_zh: "老虎是體型最大的貓科動物，也是兇猛的掠食者。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Lion",
        correct: true,
        translation: "獅子",
        fact: "Lions are often called 'King of the Jungle' due to their majestic appearance and position as apex predators, even though they primarily live in savannas, not jungles.",
        fact_zh:
          "獅子因其雄偉的外表和頂級掠食者的地位，常被稱為「森林之王」，儘管牠們主要生活在草原而非叢林。",
        correctFact:
          "Male lions are easily recognizable by their impressive manes, which can vary in color and size.",
        correctFact_zh:
          "公獅子很容易透過牠們威武的鬃毛來辨認，鬃毛的顏色和大小各不相同。雖然叫森林之王，但牠們其實比較像草原霸主呢！",
      },
      {
        text: "Elephant",
        correct: false,
        translation: "大象",
        fact: "Elephants are the largest land animals.",
        fact_zh: "大象是陸地上最大的動物。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Bear",
        correct: false,
        translation: "熊",
        fact: "Bears are large, carnivorous or omnivorous mammals.",
        fact_zh: "熊是大型的食肉或雜食哺乳動物。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question:
      "What gas do plants absorb from the atmosphere for photosynthesis?",
    translation: "植物行光合作用時會從大氣中吸收什麼氣體？",
    answers: [
      {
        text: "Oxygen",
        correct: false,
        translation: "氧氣",
        fact: "Oxygen is what humans and animals breathe.",
        fact_zh: "氧氣是人類和動物呼吸所需的氣體。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Nitrogen",
        correct: false,
        translation: "氮氣",
        fact: "Nitrogen is the most abundant gas in Earth's atmosphere.",
        fact_zh: "氮氣是地球大氣中最豐富的氣體。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Carbon Dioxide",
        correct: true,
        translation: "二氧化碳",
        fact: "Plants use carbon dioxide for photosynthesis, converting it into oxygen and sugars.",
        fact_zh: "植物利用二氧化碳進行光合作用，將其轉化為氧氣和糖分。",
        correctFact:
          "This process is crucial for life on Earth, as it produces the oxygen we breathe and forms the base of most food chains.",
        correctFact_zh:
          "這個過程對地球上的生命至關重要，因為它產生了我們呼吸的氧氣，並構成了大多數食物鏈的基礎。可以說是地球生命的空氣清淨機兼廚師！",
      },
      {
        text: "Hydrogen",
        correct: false,
        translation: "氫氣",
        fact: "Hydrogen is the lightest element and rarely found as a free gas in Earth's atmosphere.",
        fact_zh: "氫氣是最輕的元素，在地球大氣中很少以游離氣體形式存在。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What do bees make?",
    translation: "蜜蜂會製造什麼？",
    answers: [
      {
        text: "Syrup",
        correct: false,
        translation: "糖漿",
        fact: "Syrup is a thick, viscous liquid made from sugar.",
        fact_zh: "糖漿是由糖製成的濃稠液體，跟蜂蜜不一樣喔。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Honey",
        correct: true,
        translation: "蜂蜜",
        fact: "Bees produce honey from the nectar of flowers, storing it as food for the hive.",
        fact_zh: "蜜蜂從花蜜中製造蜂蜜，並將其儲存為蜂巢的食物。",
        correctFact:
          "Honey is known for its natural sweetness and has been used by humans for thousands of years as food and medicine.",
        correctFact_zh:
          "蜂蜜以其天然甜味而聞名，數千年來一直被人類用作食物和藥物。真是辛苦的小小甜點師傅！",
      },
      {
        text: "Pollen",
        correct: false,
        translation: "花粉",
        fact: "Bees collect pollen as a protein source, but they don't 'make' it.",
        fact_zh: "蜜蜂收集花粉作為蛋白質來源，但牠們並不「製造」花粉。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Wax",
        correct: false,
        translation: "蜂蠟",
        fact: "Bees produce beeswax to build their honeycombs, but honey is their primary food product.",
        fact_zh: "蜜蜂分泌蜂蠟來建造蜂巢，但蜂蜜才是牠們主要的食物產品。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "How many days are in a week?",
    translation: "一星期有幾天？",
    answers: [
      {
        text: "5",
        correct: false,
        translation: "5天",
        fact: "A standard work week often has 5 days.",
        fact_zh: "標準工作週通常是5天，但一星期不只這樣。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "6",
        correct: false,
        translation: "6天",
        fact: "Some cultures or work schedules might have 6 days.",
        fact_zh: "某些文化或工作排程可能是一週6天。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "7",
        correct: true,
        translation: "7天",
        fact: "A week traditionally consists of seven days.",
        fact_zh: "一星期傳統上包含七天。",
        correctFact:
          "The seven-day week has ancient origins, possibly linked to the phases of the moon or astronomical observations.",
        correctFact_zh:
          "七天一星期的制度起源古老，可能與月相或天文觀測有關。這是全世界通用的時間單位呢！",
      },
      {
        text: "8",
        correct: false,
        translation: "8天",
        fact: "An eight-day week is not a common calendar unit.",
        fact_zh: "八天一星期並不是常見的曆法單位。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the opposite of 'hot'?",
    translation: "「熱」的相反詞是什麼？",
    answers: [
      {
        text: "Warm",
        correct: false,
        translation: "溫暖",
        fact: "Warm is a moderate temperature, not the extreme opposite.",
        fact_zh: "溫暖是適中的溫度，不是極端的相反。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Cold",
        correct: true,
        translation: "冷",
        fact: "Cold is the absence of heat or a low temperature.",
        fact_zh: "冷是指缺乏熱量或溫度低。",
        correctFact:
          "Temperature is a measure of the average kinetic energy of particles in a substance; cold indicates less kinetic energy.",
        correctFact_zh:
          "溫度是衡量物質中粒子平均動能的指標；冷表示動能較少。就像台灣的夏天跟冬天一樣對比強烈！",
      },
      {
        text: "Spicy",
        correct: false,
        translation: "辣",
        fact: "Spicy describes a taste sensation, not a temperature.",
        fact_zh: "辣描述的是一種味覺感受，不是溫度。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Freezing",
        correct: false,
        translation: "冰凍",
        fact: "Freezing is a very low temperature, but 'cold' is the direct opposite of 'hot'.",
        fact_zh: "冰凍是非常低的溫度，但「冷」才是「熱」的直接相反詞。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Which animal says 'moo'?",
    translation: "哪種動物會發出「哞」的叫聲？",
    answers: [
      {
        text: "Sheep",
        correct: false,
        translation: "綿羊",
        fact: "Sheep say 'baa'.",
        fact_zh: "綿羊是「咩咩」叫。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Goat",
        correct: false,
        translation: "山羊",
        fact: "Goats make a bleating sound.",
        fact_zh: "山羊也是發出「咩咩」類似的叫聲。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Cow",
        correct: true,
        translation: "牛",
        fact: "Cows are well-known for their 'moo' sound.",
        fact_zh: "牛以其「哞」叫聲而聞名。",
        correctFact:
          "Cows moo for various reasons, including communicating with their calves, expressing hunger, or indicating distress.",
        correctFact_zh:
          "牛哞哞叫的原因有很多，包括與小牛溝通、表達飢餓或表示不安。在鄉下比較容易聽到牠們的歌聲！",
      },
      {
        text: "Pig",
        correct: false,
        translation: "豬",
        fact: "Pigs say 'oink'.",
        fact_zh: "豬是「哼哼」叫。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What color are bananas typically when ripe?",
    translation: "香蕉成熟時通常是什麼顏色？",
    answers: [
      {
        text: "Green",
        correct: false,
        translation: "綠色",
        fact: "Green bananas are unripe.",
        fact_zh: "綠色香蕉是未成熟的，比較澀。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Yellow",
        correct: true,
        translation: "黃色",
        fact: "Ripe bananas are typically bright yellow.",
        fact_zh: "成熟的香蕉通常是鮮黃色的。",
        correctFact:
          "As bananas ripen, the starch in them converts to sugar, making them sweeter and changing their color from green to yellow.",
        correctFact_zh:
          "香蕉成熟時，其中的澱粉會轉化為糖分，使其變得更甜，顏色也從綠色變為黃色。台灣的香蕉世界有名喔！",
      },
      {
        text: "Red",
        correct: false,
        translation: "紅色",
        fact: "Some rare varieties of bananas can be red or pink.",
        fact_zh: "有些稀有品種的香蕉可能是紅色或粉紅色的。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Brown",
        correct: false,
        translation: "棕色",
        fact: "Brown spots on a banana indicate it's very ripe or overripe.",
        fact_zh: "香蕉上的棕色斑點表示它非常成熟或過熟了。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the shape of the Earth?",
    translation: "地球是什麼形狀的？",
    answers: [
      {
        text: "Flat",
        correct: false,
        translation: "平的",
        fact: "The flat Earth theory is a historical misconception.",
        fact_zh: "地平說是一種歷史上的誤解，地球其實不是平的。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Square",
        correct: false,
        translation: "方形的",
        fact: "A square has four equal sides and is a 2D shape.",
        fact_zh: "正方形有四條等長的邊，是一個二維圖形。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Round (Sphere)",
        correct: true,
        translation: "圓形 (球體)",
        fact: "The Earth is an oblate spheroid, meaning it's a sphere that is slightly flattened at the poles and bulging at the equator.",
        fact_zh:
          "地球是一個扁球體，意思是它是一個在兩極略扁、在赤道略鼓的球體。",
        correctFact:
          "This shape is a result of its rotation, which creates centrifugal force that pushes material outward at the equator.",
        correctFact_zh:
          "這種形狀是其自轉造成的結果，自轉產生的離心力使物質在赤道向外突出。從外太空看，地球就像一顆美麗的彈珠！",
      },
      {
        text: "Triangle",
        correct: false,
        translation: "三角形",
        fact: "A triangle is a 2D shape with three sides.",
        fact_zh: "三角形是一個有三條邊的二維圖形。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "How many fingers are on one human hand (excluding the thumb)?",
    translation: "一隻手有幾根手指（不包括拇指）？",
    answers: [
      {
        text: "Three",
        correct: false,
        translation: "三根",
        fact: "Three fingers would be missing a digit.",
        fact_zh: "三根手指就少了一根囉。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Four",
        correct: true,
        translation: "四根",
        fact: "Excluding the thumb, a human hand has four fingers: index, middle, ring, and pinky.",
        fact_zh: "不包括拇指，一隻手有四根手指：食指、中指、無名指和小指。",
        correctFact:
          "The thumb is distinct from the other four digits due to its opposable nature, allowing for gripping and manipulation.",
        correctFact_zh:
          "拇指與其他四指不同，因為它具有對握性，可以抓握和操控物體。我們的雙手真是萬能！",
      },
      {
        text: "Five",
        correct: false,
        translation: "五根",
        fact: "Five fingers would include the thumb.",
        fact_zh: "五根手指就包含拇指了。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Six",
        correct: false,
        translation: "六根",
        fact: "Having six fingers is a condition called polydactyly.",
        fact_zh: "有六根手指是一種稱為多指畸形的狀況。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the opposite of 'up'?",
    translation: "「上」的相反詞是什麼？",
    answers: [
      {
        text: "Left",
        correct: false,
        translation: "左",
        fact: "Left is a directional opposite on a horizontal plane.",
        fact_zh: "左是在水平面上的方向相反詞。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Right",
        correct: false,
        translation: "右",
        fact: "Right is another directional opposite on a horizontal plane.",
        fact_zh: "右也是在水平面上的方向相反詞。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Down",
        correct: true,
        translation: "下",
        fact: "Down is the direct opposite direction of up, typically towards the ground.",
        fact_zh: "下是上的直接相反方向，通常指向地面。",
        correctFact:
          "In physics, 'down' is often associated with the direction of gravitational pull.",
        correctFact_zh:
          "在物理學中，「下」通常與重力方向相關。就像我們常說的「人生有起有落」一樣。",
      },
      {
        text: "Sideways",
        correct: false,
        translation: "旁邊",
        fact: "Sideways refers to a movement or position to the side.",
        fact_zh: "旁邊指的是向側面移動或位置。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "Which meal is usually eaten in the morning?",
    translation: "哪一餐通常在早上吃？",
    answers: [
      {
        text: "Lunch",
        correct: false,
        translation: "午餐",
        fact: "Lunch is typically eaten around midday.",
        fact_zh: "午餐通常在中午左右吃。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Dinner",
        correct: false,
        translation: "晚餐",
        fact: "Dinner is the main meal of the day, usually eaten in the evening.",
        fact_zh: "晚餐是一天中的主餐，通常在晚上吃。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Breakfast",
        correct: true,
        translation: "早餐",
        fact: "Breakfast is the first meal of the day, usually eaten in the morning.",
        fact_zh: "早餐是一天中的第一餐，通常在早上吃。",
        correctFact:
          "The word 'breakfast' literally means 'breaking the fast' from the previous night's sleep.",
        correctFact_zh:
          "「Breakfast」這個詞的字面意思是「打破齋戒」，指結束前一晚睡眠後的禁食狀態。在台灣，早餐選擇超多樣！",
      },
      {
        text: "Snack",
        correct: false,
        translation: "點心",
        fact: "A snack is a small amount of food eaten between meals.",
        fact_zh: "點心是在兩餐之間吃少量食物。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What do fish use to breathe underwater?",
    translation: "魚在水裡用什麼呼吸？",
    answers: [
      {
        text: "Lungs",
        correct: false,
        translation: "肺",
        fact: "Lungs are used by air-breathing animals like humans.",
        fact_zh: "肺是像人類這樣的陸生動物呼吸用的。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Gills",
        correct: true,
        translation: "鰓",
        fact: "Fish use gills to extract oxygen from the water.",
        fact_zh: "魚用鰓從水中提取氧氣。",
        correctFact:
          "Gills are feathery organs that contain many blood vessels, allowing for efficient gas exchange.",
        correctFact_zh:
          "鰓是羽毛狀的器官，含有許多血管，可以有效地進行氣體交換。真是神奇的設計！",
      },
      {
        text: "Skin",
        correct: false,
        translation: "皮膚",
        fact: "While some aquatic animals can absorb oxygen through their skin, it's not the primary method for most fish.",
        fact_zh:
          "雖然有些水生動物可以透過皮膚吸收氧氣，但這不是大多數魚類的主要呼吸方式。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Fins",
        correct: false,
        translation: "鰭",
        fact: "Fins are used by fish for movement and balance.",
        fact_zh: "魚用鰭來移動和保持平衡。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "How many sides does a triangle have?",
    translation: "三角形有幾條邊？",
    answers: [
      {
        text: "2",
        correct: false,
        translation: "2條",
        fact: "A shape with 2 sides is not a triangle.",
        fact_zh: "有2條邊的圖形不是三角形。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "3",
        correct: true,
        translation: "3條",
        fact: "A triangle is a polygon with three edges and three vertices.",
        fact_zh: "三角形是一個有三個邊和三個頂點的多邊形。",
        correctFact:
          "The sum of the interior angles of a triangle in Euclidean geometry is always 180 degrees.",
        correctFact_zh:
          "在歐幾里得幾何學中，三角形的內角和總是180度。這是數學的基本功喔！",
      },
      {
        text: "4",
        correct: false,
        translation: "4條",
        fact: "A shape with 4 sides is typically a quadrilateral, like a square or rectangle.",
        fact_zh: "有4條邊的圖形通常是四邊形，如正方形或長方形。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "5",
        correct: false,
        translation: "5條",
        fact: "A shape with 5 sides is a pentagon.",
        fact_zh: "有5條邊的圖形是五邊形。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the name of a baby dog?",
    translation: "小狗的稱呼是什麼？",
    answers: [
      {
        text: "Kitten",
        correct: false,
        translation: "小貓",
        fact: "A kitten is a baby cat.",
        fact_zh: "Kitten 是指幼貓。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Calf",
        correct: false,
        translation: "小牛",
        fact: "A calf is a baby cow.",
        fact_zh: "Calf 是指幼牛。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Puppy",
        correct: true,
        translation: "小狗",
        fact: "A baby dog is called a puppy.",
        fact_zh: "幼犬 (Puppy) 是指年紀小的狗。",
        correctFact:
          "Puppies are born blind and deaf, and their eyes and ears open after about two weeks.",
        correctFact_zh:
          "Puppy 剛出生時眼睛看不見，耳朵也聽不見，大約兩週後眼睛和耳朵才會張開。是不是超可愛！",
      },
      {
        text: "Foal",
        correct: false,
        translation: "小馬",
        fact: "A foal is a baby horse.",
        fact_zh: "Foal 是指幼馬。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What do you typically wear on your feet to go outside?",
    translation: "你出門時通常在腳上穿什麼？",
    answers: [
      {
        text: "Gloves",
        correct: false,
        translation: "手套",
        fact: "Gloves are worn on hands.",
        fact_zh: "手套是戴在手上的。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Hat",
        correct: false,
        translation: "帽子",
        fact: "A hat is worn on the head.",
        fact_zh: "帽子是戴在頭上的。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Shoes",
        correct: true,
        translation: "鞋子",
        fact: "Shoes are worn on the feet for protection and comfort.",
        fact_zh: "鞋子穿在腳上，用於保護和舒適。",
        correctFact:
          "There are many types of shoes, designed for various activities and weather conditions.",
        correctFact_zh:
          "鞋子有很多種類型，專為各種活動和天氣條件設計。台灣夏天很多人愛穿拖鞋趴趴走！",
      },
      {
        text: "Scarf",
        correct: false,
        translation: "圍巾",
        fact: "A scarf is worn around the neck or head.",
        fact_zh: "圍巾是圍在脖子或頭上的。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the main color of grass?",
    translation: "草的主要顏色是什麼？",
    answers: [
      {
        text: "Blue",
        correct: false,
        translation: "藍色",
        fact: "Blue is the color of the sky.",
        fact_zh: "藍色是天空的顏色。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Green",
        correct: true,
        translation: "綠色",
        fact: "Grass is green due to the presence of chlorophyll, a pigment essential for photosynthesis.",
        fact_zh:
          "草是綠色的，因為含有葉綠素，這是一種對光合作用至關重要的色素。",
        correctFact:
          "Chlorophyll absorbs red and blue light, reflecting green light, which is why plants appear green to our eyes.",
        correctFact_zh:
          "葉綠素吸收紅光和藍光，反射綠光，這就是為什麼植物在我們眼中呈現綠色。公園裡的草地讓人看了心情很好！",
      },
      {
        text: "Yellow",
        correct: false,
        translation: "黃色",
        fact: "Yellow grass might indicate it's dry or dying.",
        fact_zh: "黃色的草可能表示它乾枯或快死了。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Red",
        correct: false,
        translation: "紅色",
        fact: "Red is not a typical color for grass.",
        fact_zh: "紅色不是草的典型顏色。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the sound a cat makes?",
    translation: "貓會發出什麼聲音？",
    answers: [
      {
        text: "Bark",
        correct: false,
        translation: "汪汪",
        fact: "Dogs bark.",
        fact_zh: "狗才會汪汪叫。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Moo",
        correct: false,
        translation: "哞哞",
        fact: "Cows moo.",
        fact_zh: "牛才會哞哞叫。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Meow",
        correct: true,
        translation: "喵喵",
        fact: "Cats are known for their distinctive 'meow' sound.",
        fact_zh: "貓以其獨特的「喵喵」聲而聞名。",
        correctFact:
          "A cat's meow can convey various messages, from greetings to demands for attention or food.",
        correctFact_zh:
          "貓的喵喵叫可以傳達各種訊息，從打招呼到要求關注或食物。貓奴們最懂牠們的語言了！",
      },
      {
        text: "Chirp",
        correct: false,
        translation: "啾啾",
        fact: "Birds chirp.",
        fact_zh: "鳥才會啾啾叫。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "How many wheels does a bicycle have?",
    translation: "腳踏車有幾個輪子？",
    answers: [
      {
        text: "1",
        correct: false,
        translation: "1個",
        fact: "A unicycle has 1 wheel.",
        fact_zh: "獨輪車有1個輪子。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "2",
        correct: true,
        translation: "2個",
        fact: "A bicycle is named for its two wheels.",
        fact_zh: "腳踏車因其有兩個輪子而得名。",
        correctFact:
          "The word 'bicycle' comes from the Greek prefix 'bi-' meaning two, and 'kyklos' meaning circle or wheel.",
        correctFact_zh:
          "「bicycle」這個詞來自希臘語前綴「bi-」（意為二）和「kyklos」（意為圓圈或輪子）。在台灣騎YouBike很方便！",
      },
      {
        text: "3",
        correct: false,
        translation: "3個",
        fact: "A tricycle has 3 wheels.",
        fact_zh: "三輪車有3個輪子。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "4",
        correct: false,
        translation: "4個",
        fact: "A car typically has 4 wheels.",
        fact_zh: "汽車通常有4個輪子。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the opposite of 'big'?",
    translation: "「大」的相反詞是什麼？",
    answers: [
      {
        text: "Large",
        correct: false,
        translation: "大的 (Large)",
        fact: "Large is a synonym for big.",
        fact_zh: "Large 是 big 的同義詞。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Huge",
        correct: false,
        translation: "巨大的",
        fact: "Huge means extremely large.",
        fact_zh: "Huge 的意思是極其大。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Small",
        correct: true,
        translation: "小",
        fact: "Small means of a limited size or extent.",
        fact_zh: "Small 的意思是尺寸或範圍有限。",
        correctFact:
          "The concept of 'small' is relative and can vary greatly depending on the context.",
        correctFact_zh:
          "「小」的概念是相對的，並且會因情境而有很大差異。就像台灣雖小，五臟俱全！",
      },
      {
        text: "Giant",
        correct: false,
        translation: "巨人般的",
        fact: "Giant refers to something exceptionally large.",
        fact_zh: "Giant 指的是異常巨大的東西。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What do birds use to fly?",
    translation: "鳥用什麼來飛行？",
    answers: [
      {
        text: "Legs",
        correct: false,
        translation: "腿",
        fact: "Birds use their legs for perching and walking.",
        fact_zh: "鳥用腿來棲息和行走。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Fins",
        correct: false,
        translation: "鰭",
        fact: "Fins are used by fish for swimming.",
        fact_zh: "魚用鰭來游泳。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Wings",
        correct: true,
        translation: "翅膀",
        fact: "Birds use their wings, covered in feathers, to generate lift and thrust for flight.",
        fact_zh: "鳥用覆蓋著羽毛的翅膀產生升力和推力來飛行。",
        correctFact:
          "The shape and structure of a bird's wings are adapted for efficient aerodynamics, allowing for various flight patterns.",
        correctFact_zh:
          "鳥翅膀的形狀和結構適合高效的空氣動力學，可以實現各種飛行模式。真是大自然的奇蹟！",
      },
      {
        text: "Tails",
        correct: false,
        translation: "尾巴",
        fact: "Birds use their tails for steering and balance during flight.",
        fact_zh: "鳥在飛行時用尾巴來控制方向和保持平衡。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the name of the big star in our solar system?",
    translation: "我們太陽系中那顆大恆星叫什麼名字？",
    answers: [
      {
        text: "Moon",
        correct: false,
        translation: "月亮",
        fact: "The Moon is Earth's natural satellite.",
        fact_zh: "月亮是地球的天然衛星。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Mars",
        correct: false,
        translation: "火星",
        fact: "Mars is a planet in our solar system.",
        fact_zh: "火星是我們太陽系中的一顆行星。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Sun",
        correct: true,
        translation: "太陽",
        fact: "The Sun is the star at the center of our solar system, providing light and heat to Earth.",
        fact_zh: "太陽是我們太陽系中心的恆星，為地球提供光和熱。",
        correctFact:
          "It is a G-type main-sequence star and makes up about 99.86% of the total mass of the Solar System.",
        correctFact_zh:
          "它是一顆G型主序星，約佔太陽系總質量的99.86%。少了它，地球就GG了！",
      },
      {
        text: "Earth",
        correct: false,
        translation: "地球",
        fact: "Earth is the planet we live on.",
        fact_zh: "地球是我們居住的行星。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What do you wear on your head to keep warm in winter?",
    translation: "冬天你在頭上戴什麼來保暖？",
    answers: [
      {
        text: "Gloves",
        correct: false,
        translation: "手套",
        fact: "Gloves are worn on hands.",
        fact_zh: "手套是戴在手上的。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Scarf",
        correct: false,
        translation: "圍巾",
        fact: "A scarf is worn around the neck.",
        fact_zh: "圍巾是圍在脖子上的。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Hat",
        correct: true,
        translation: "帽子",
        fact: "A hat covers the head and can provide warmth in cold weather.",
        fact_zh: "帽子蓋住頭部，可以在寒冷的天氣裡提供溫暖。",
        correctFact:
          "Wearing a hat helps prevent heat loss from the head, which is a significant area for body temperature regulation.",
        correctFact_zh:
          "戴帽子有助於防止頭部熱量流失，頭部是身體調節體溫的重要區域。台灣的冬天有時也需要毛帽！",
      },
      {
        text: "Socks",
        correct: false,
        translation: "襪子",
        fact: "Socks are worn on feet.",
        fact_zh: "襪子是穿在腳上的。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the name of a place where books are kept and borrowed?",
    translation: "存放和借閱書籍的地方叫什麼？",
    answers: [
      {
        text: "Museum",
        correct: false,
        translation: "博物館",
        fact: "A museum is a place for displaying artifacts and art.",
        fact_zh: "博物館是展示文物和藝術品的地方。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Cinema",
        correct: false,
        translation: "電影院",
        fact: "A cinema is a place to watch movies.",
        fact_zh: "電影院是看電影的地方。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Library",
        correct: true,
        translation: "圖書館",
        fact: "A library is a building or room containing collections of books, periodicals, and sometimes films and recorded music for people to read, borrow, or refer to.",
        fact_zh:
          "圖書館是收藏書籍、期刊，有時還有電影和唱片供人們閱讀、借閱或參考的建築物或房間。",
        correctFact:
          "Libraries play a vital role in communities by providing access to information, fostering literacy, and offering educational programs.",
        correctFact_zh:
          "圖書館透過提供資訊、培養讀寫能力和提供教育計畫，在社區中扮演著至關重要的角色。台灣有很多特色圖書館喔！",
      },
      {
        text: "Hospital",
        correct: false,
        translation: "醫院",
        fact: "A hospital is a place for medical treatment.",
        fact_zh: "醫院是接受醫療的地方。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
  {
    question: "What is the currency of Japan?",
    translation: "日本的貨幣是什麼？",
    answers: [
      {
        text: "Yuan",
        correct: false,
        translation: "元",
        fact: "The Yuan is the currency of China.",
        fact_zh: "元是中國的貨幣單位。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Won",
        correct: false,
        translation: "韓元",
        fact: "The Won is the currency of South Korea and North Korea.",
        fact_zh: "韓元是韓國的貨幣。",
        correctFact: null,
        correctFact_zh: null,
      },
      {
        text: "Yen",
        correct: true,
        translation: "日圓",
        fact: "The Japanese Yen is the official currency of Japan.",
        fact_zh: "日圓是日本的官方貨幣。",
        correctFact:
          "It is the third most traded currency in the foreign exchange market after the United States dollar and the Euro.",
        correctFact_zh:
          "日圓是外匯市場上交易量第三大的貨幣，僅次於美元和歐元。很多台灣人喜歡去日本玩，所以對日圓不陌生！",
      },
      {
        text: "Baht",
        correct: false,
        translation: "泰銖",
        fact: "The Baht is the currency of Thailand.",
        fact_zh: "泰銖是泰國的貨幣。",
        correctFact: null,
        correctFact_zh: null,
      },
    ],
  },
];
